---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 3.1 Set Daemon umask (Scored)
    lineinfile: >
      dest=/etc/sysconfig/init
      state=present
      regexp=^umask
      line="umask 027"

  - name: 3.2 Remove X Windows (runlevel 3) (Scored)
    lineinfile: >
      dest=/etc/inittab
      state=present
      regexp="^id:"
      line="id:3:initdefault:"

  - name: 3.2 Remove X Windows (remove package group) (Scored)
    yum: >
      name=xorg-x11-server-common
      state=absent

  - name: 3.3 Disable Avahi Server (check if installed) (Scored)
    stat: path=/etc/init.d/avahi-daemon
    register: avahi_service

  - name: 3.3 Disable Avahi Server (disable service) (Scored)
    service: >
      name=avahi-daemon
      state=stopped
      enabled=no
    when: avahi_service.stat.exists

  - name: 3.4 Check to see if cups daemon is installed (Not Scored)
    stat: path=/etc/init.d/cups
    register: cups_service

  - name: 3.4 Disable Print Server - CUPS (Not Scored)
    service: >
      name=cups
      state=stopped
      enabled=no
    ignore_errors: yes
    when: cups_service.stat.exists

  - name: 3.5 Remove DHCP Server (Score)
    yum: >
      name=dhcp
      state=absent

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    yum: >
      name=ntp
      state=present

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    service: >
      name=ntpd
      state=started
      enabled=yes

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^restrict default"
      line="restrict default kod nomodify notrap nopeer noquery"
      insertafter=EOF

  - name: 3.6 Configure Network Time Protocol (ipv6) (Scored)
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^restrict -6 default"
      line="restrict -6 default kod nomodify notrap nopeer noquery"
      insertafter=EOF

  - name: 3.7 Remove LDAP (Not Scored)
    yum: >
      name=openldap-clients
      state=absent
    when: not ldap_client

  - name: 3.7 Remove LDAP (Not Scored)
    yum: >
      name=openldap-servers
      state=absent
    when: not ldap_server

  - name: 3.8 Disable NFS and RPC (check for nfs-utils) (Not Scored)
    stat: path=/etc/init.d/nfslock
    register: nfs_utils

  - name: 3.8 Disable NFS and RPC (check for rpcbind) (Not Scored)
    stat: path=/etc/init.d/rpcbind
    register: rpcbind

  - name: 3.8 Disable NFS and RPC (nfs-utils services) (Not Scored)
    service: >
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
      - nfslock
      - rpcgssd
      - rpcidmapd
      - rpcsvcgssd
    when: nfs_utils.stat.exists

  - name: 3.8 Disable NFS and RPC (rpcbind services)
    service: >
      name=rpcbind
      state=stopped
      enabled=no
    when:
      - rpcbind.stat.exists
      - not nfs

  - name: 3.9 Remove DNS Server
    yum: >
      name=bind
      state=absent
    when: not dns

  - name: 3.10 Remove FTP Server
    yum: >
      name=vsftpd
      state=absent
    when: not ftp

  - name: 3.11 Remove HTTP Server
    yum: >
      name=httpd
      state=absent
    when: not httpd

  - name: 3.12 Remove Dovecot
    yum: >
      name=dovecot
      state=absent
    when: not dovecot

  - name: 3.13 Remove Samba
    yum: >
      name=samba
      state=absent
    when: not samba

  - name: 3.14 Remove HTTP Proxy Server
    yum: >
      name=squid
      state=absent
    when: not squid

  - name: 3.15 Remove SNMP Server
    yum: >
      name=net-snmp
      state=absent
    when: not snmp

  - name: 3.16 Configure Mail Transfer Agent for Local-Only Mode
    lineinfile: >
      dest=/etc/postfix/main.cf
      state=present
      regexp="^inet_interfaces"
      line="inet_interfaces = localhost"
      insertafter=EOF
