---
# CIS Benchmarks Section 3

  - name: 3.1 Set Daemon umask
    lineinfile: dest=/etc/sysconfig/init state=present regexp=^umask line="umask 027"
  - name: 3.2 Remove X Windows (runlevel 3)
    lineinfile: dest=/etc/inittab state=present regexp="^id:" line="id:3:initdefault:"
  - name: 3.2 Remove X Windows (remove package group)
    yum: name="@X Window System" state=absent
  - name: 3.3 Disable Avahi Server
    command: chkconfig avahi-daemon off removes=/etc/rc.d/rc3.d/S24avahi-daemon
  - name: 3.5 Remove DHCP Server
    yum: name=dhcp state=absent
  - name: 3.6 Configure Network Time Protocol (ipv4)
    lineinfile: dest=/etc/ntp.conf state=present regexp="^restrict default" line="restrict default kod nomodify notrap nopeer noquery" insertafter=EOF
  - name: 3.6 Configure Network Time Protocol (ipv6)
    lineinfile: dest=/etc/ntp.conf state=present regexp="^restrict -6 default" line="restrict -6 default kod nomodify notrap nopeer noquery" insertafter=EOF
  - name: 3.16 Configure Mail Transfer Agent for Local-Only Mode
    lineinfile: dest=/etc/postfix/main.cf state=present regexp="^inet_interfaces" line="inet_interfaces = localhost" insertafter=EOF