---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 1.1.1 - 1.1.4 Configure /tmp Partition
    mount: >
      name="/tmp"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev,nosuid,noexec"
    when: item.mount == "/tmp"
    with_items: ansible_mounts

  - name: 1.1.5 Create Separate Partition for /var
    debug: msg="Manually create Separate Partition for /var."

  - name: 1.1.6 Bind Mount the /var/tmp directory to /tmp
    mount: >
      name="/var/tmp"
      src="/tmp"
      state=mounted
      fstype="none"
      opts="bind"
    when: item.mount == "/tmp"
    with_items: ansible_mounts

  - name: 1.1.7 Create Separate Partition for /var/log
    debug: msg="Manually create Separate Partition for /var/log."

  - name: 1.1.8 Create Separate Partition for /var/log/audit 
    debug: msg="Manually create Separate Partition for /var/log/audit."

  - name: 1.1.9 - 1.1.10 Configure /home Partition
    mount: >
      name="/home"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev"
    when: item.mount == "/home"
    with_items: ansible_mounts

  - name: 1.1.11 Add nodev Option to Removable Media Partitions 
    debug: msg="Not relevant."

  - name: 1.1.12 Add noexec Option to Removable Media Partitions
    debug: msg="Not relevant."

  - name: 1.1.13 Add nosuid Option to Removable Media Partitions
    debug: msg="Not relevant."

  - name: 1.1.14 - 1.1.16 Configure /dev/shm Partition
    mount: >
      name="/dev/shm"
      src="none"
      state=mounted
      fstype="tmpfs"
      opts="nodev,nosuid,noexec"

  - name: 1.1.17 Set sticky bit on all world-writeable directories
    debug: msg="Too destructive -- see notes"

  - name: 1.1.18 Disable Mounting of cramfs Filesystems
    lineinfile: >
      state=present 
      create=yes 
      dest=/etc/modprobe.d/CIS.conf 
      line="install cramfs /bin/true"
  
  - name: 1.1.19 Disable Mounting of freevxfs Filesystems
    lineinfile: >
      state=present 
      dest=/etc/modprobe.d/CIS.conf 
      line="install freevxfs /bin/true"
  
  - name: 1.1.20 Disable Mounting of jffs2 Filesystems
    lineinfile: >
      state=present 
      dest=/etc/modprobe.d/CIS.conf 
      line="install jffs2 /bin/true"
  
  - name: 1.1.21 Disable Mounting of hfs Filesystems
    lineinfile: >
      state=present 
      dest=/etc/modprobe.d/CIS.conf 
      line="install hfs /bin/true"

  - name: 1.1.22 Disable Mounting of hfsplus Filesystems
    lineinfile: >
      state=present 
      dest=/etc/modprobe.d/CIS.conf 
      line="install hfsplus /bin/true"

  - name: 1.1.23 Disable Mounting of squashfs Filesystems
    lineinfile: >
      state=present 
      dest=/etc/modprobe.d/CIS.conf 
      line="install squashfs /bin/true"

  - name: 1.1.24 Disable Mounting of udf Filesystems
    lineinfile: >
      state=present 
      dest=/etc/modprobe.d/CIS.conf 
      line="install udf /bin/true"

  - name: 1.2.1 Configure connection to the RHN RPM repositories
    command: yum check-update
    when: ansible_distribution == "RedHat"

  - name: 1.2.2 Verify Red Hat GPG key is installed
    command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
    when: ansible_distribution == "RedHat"

  - name: 1.2.3 Verify that gpgcheck is Globally Activated
    lineinfile: >
      state=present
      dest=/etc/yum.conf
      regexp=^gpgcheck=
      line=gpgcheck=1

  - name: 1.2.5 Obtain software package updates with yum
    debug: msg="Check manually."

  - name: 1.2.6 Verify package integrity using RPM
    debug: msg="Check via cron/AIDE/manually"

  - name: 1.5.1 Set User/Group Owner on /etc/grub.conf
    file: >
      path=/etc/grub.conf
      owner=root
      group=root

  - name: 1.5.2 Set Permissions on /etc/grub.conf
    file: >
      path=/etc/grub.conf
      mode=0400

  - name: 1.5.3 Set boot loader password
    debug: msg="Too destructive for production systems. Evaluate for your environment first."

  - name: 1.5.4 Require authentication for single-user mode
    debug: msg="Too destructive for production systems. Evaluate for your environment first."

  - name: 1.5.5 Disable Interactive Boot
    lineinfile: >
      dest=/etc/sysconfig/init
      regexp=^PROMPT=
      line=PROMPT=no

  - name: 1.6.1 Restrict core dumps (via pam)
    lineinfile: >
      dest=/etc/security/limits.conf
      line="* hard core 0"
      insertafter=EOF

  - name: 1.6.1 Restrict core dumps (via sysctl)
    sysctl: >
      name=fs.suid_dumpable
      value=0
      state=present
      ignoreerrors=yes

  - name: 1.6.2 Configure ExecShield 
    sysctl: >
      name=kernel.exec-shield
      value=1
      state=present
      ignoreerrors=yes

  - name: 1.6.3 Enable Randomized Virtual Memory Region Placement
    sysctl: >
      name=kernel.randomize_va_space
      value=2
      state=present
      ignoreerrors=yes
