---

  - name: 8.1 Set Warning Banner for Standard Login Services
    copy: >
      src=etc/{{ item }}
      dest=/etc/{{ item }}
    with_items:
      - motd
      - issue
      - issue.net

  - name: 8.1 Set Warning Banner for Standard Login Services
    file: >
      path=/etc/{{ item }}
      owner=root
      group=root
      mode=0644
    with_items:
      - motd
      - issue
      - issue.net

