---

  - name: 5.2.1.1 Configure Data Retention
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^max_log_file ="
      line="max_log_file = {{ max_log_file }}"
    notify: Reload auditd Rules

  - name: 5.2.1.2 Disable System on Audit Log Full
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^space_left_action ="
      line="space_left_action = {{ space_left_action }}"
    notify: Reload auditd Rules

  - name: 5.2.1.2 Disable System on Audit Log Full
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^action_mail_acct ="
      line="action_mail_acct = {{ action_mail_acct }}"
    notify: Reload auditd Rules

  - name: 5.2.1.2 Disable System on Audit Log Full
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^admin_space_left_action ="
      line="admin_space_left_action = {{ admin_space_left_action }}"
    notify: Reload auditd Rules

  - name: 5.2.1.3 Keep All Auditing Information
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^max_log_file_action ="
      line="max_log_file_action = {{ max_log_file_action }}"
    notify: Reload auditd Rules

  - name: 5.2.2 Enable auditd Service
    service: >
      name=auditd
      enabled=yes
      state=running

  - name: 5.2.3 Enable Auditing for Processes That Start Prior to auditd
    lineinfile: >
      state=present
      dest=/etc/grub.conf
      backrefs=yes
      regexp="(^\s*kernel.*)$(?<!audit=1)"
      line="\1 audit=1"

  - name: 5.2.4 - 5.2.18 Configure auditd Rules
    copy: >
      src=etc/audit/audit.rules
      dest=/etc/audit/audit.rules
    notify: Reload auditd Rules

