---

  - name: 2.1.1 Remove telnet-server
    yum: >
      name=telnet-server
      state=absent

  - name: 2.1.2 Remove telnet Clients
    yum: >
      name=telnet
      state=absent

  - name: 2.1.3 Remove rsh-server 
    yum: >
      name=rsh-server
      state=absent

  - name: 2.1.4 Remove rsh
    yum: >
      name=rsh
      state=absent

  - name: 2.1.5 Remove NIS Client
    yum: > 
      name=ypbind
      state=absent

  - name: 2.1.6 Remove NIS Server
    yum: >
      name=ypserv
      state=absent

  - name: 2.1.7 Remove tftp
    yum: >
      name=tftp
      state=absent

  - name: 2.1.8 Remove tftp-server
    yum: >
      name=tftp-server
      state=absent

  - name: 2.1.9 Remove talk
    yum: >
      name=talk
      state=absent

  - name: 2.1.10 Remove talk-server
    yum: >
      name=talk-server
      state=absent

  - name: 2.1.12 Disable chargen-dgram (check if exists)
    stat: path=/etc/xinetd.d/chargen-dgram
    register: chargen_dgram

  - name: 2.1.12 Disable chargen-dgram (disable xinetd service)
    service: >
        name=chargen-dgram
        state=stopped
        enabled=no
    when: chargen_dgram.stat.exists

  - name: 2.1.13 Disable chargen-stream (check if exists)
    stat: path=/etc/xinetd.d/chargen-stream
    register: chargen_stream

  - name: 2.1.13 Disable chargen-stream (disable xinetd service)
    service: >
        name=chargen-stream
        state=stopped
        enabled=no
    when: chargen_stream.stat.exists

  - name: 2.1.14 Disable daytime-dgram (check if exists)
    stat: path=/etc/xinetd.d/daytime-dgram
    register: daytime_dgram

  - name: 2.1.14 Disable daytime-dgram (disable xinetd service)
    service: >
        name=daytime-dgram
        state=stopped
        enabled=no
    when: daytime_dgram.stat.exists

  - name: 2.1.15 Disable daytime-stream (check if exists)
    stat: path=/etc/xinetd.d/daytime-stream
    register: daytime_stream

  - name: 2.1.15 Disable daytime-stream (disable xinetd service)
    service: >
        name=daytime-stream
        state=stopped
        enabled=no
    when: daytime_stream.stat.exists

  - name: 2.1.16 Disable echo-dgram (check if exists)
    stat: path=/etc/xinetd.d/echo-dgram
    register: echo_dgram

  - name: 2.1.16 Disable echo-dgram (disable xinetd service)
    service: >
        name=echo-dgram
        state=stopped
        enabled=no
    when: echo_dgram.stat.exists

  - name: 2.1.17 Disable echo-stream (check if exists)
    stat: path=/etc/xinetd.d/echo-stream
    register: echo_stream

  - name: 2.1.17 Disable echo-stream (disable xinetd service)
    service: >
        name=echo-stream
        state=stopped
        enabled=no
    when: echo_stream.stat.exists

  - name: 2.1.18 Disable tcpmux-server (check if exists)
    stat: path=/etc/xinetd.d/tcpmux-server
    register: tcpmux_server

  - name: 2.1.18 Disable tcpmux-server (disable xinetd service)
    service: >
        name=tcpmux-server
        state=stopped
        enabled=no
    when: tcpmux_server.stat.exists
