---

  - name: 1.1.18 Disable Mounting of cramfs Filesystems
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install cramfs /bin/true"

  - name: 1.1.19 Disable Mounting of freevxfs Filesystems
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install freevxfs /bin/true"

  - name: 1.1.20 Disable Mounting of jffs2 Filesystems
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install jffs2 /bin/true"

  - name: 1.1.21 Disable Mounting of hfs Filesystems
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install hfs /bin/true"

  - name: 1.1.22 Disable Mounting of hfsplus Filesystems
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install hfsplus /bin/true"

  - name: 1.1.23 Disable Mounting of squashfs Filesystems
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install squashfs /bin/true"

  - name: 1.1.24 Disable Mounting of udf Filesystems
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install udf /bin/true"

  - name: 1.2.4 Check to see if rhnsd daemon is installed
    stat: path=/etc/init.d/rhnsd
    register: rhnsd_service

  - name: 1.2.4 Disable the rhnsd Daemon
    service: >
      name=rhnsd
      enabled=no
      state=stopped
    when: rhnsd_service.stat.exists

  - name: 1.3.1 Install AIDE
    yum: >
      name=aide
      state=present
    when: configure_aide

  - name: 1.3.1 Install AIDE (Initialize)
    command: >
      /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz' 
      creates=/var/lib/aide/aide.db.gz
    when: configure_aide

  - name: 1.3.1 Install AIDE (check is prelink installed)
    stat: path=/usr/sbin/prelink
    register: prelink_stat

  - name: 1.3.1 Install AIDE (Disable Prelinking)
    lineinfile: >
      state=present
      dest=/etc/sysconfig/prelink
      regexp=^PRELINKING=
      line=PRELINKING=no
      create=yes
    when:
      - configure_aide
      - prelink_stat.stat.exists

  - name: 1.3.2 Implement Periodic Execution of File Integrity
    cron: >
      name="Run AIDE (CIS 1.3.2)"
      minute="0"
      hour="5"
      job="/usr/sbin/aide --check"
    when: configure_aide

  - name: 1.4.2/1.4.3 Set the SELinux State/Policy (install targeted)
    yum: >
      name=selinux-policy-targeted
      state=present

  - name: 1.4.2/1.4.3 Set the SELinux State/Policy
    selinux: >
      state=enforcing
      policy=targeted

  - name: 1.4.5 Remove MCS Translation Service
    yum: >
      name=mcstrans
      state=absent

  - name: 1.4.6 Check for unconfined daemons
    debug: msg="Check via cron jobs or manually."